# Generated by Django 5.1.2 on 2024-10-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='score',
            new_name='points',
        ),
    ]
