# Generated by Django 5.1.2 on 2024-10-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_pointevent_event_type_pointevent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointevent',
            name='description',
        ),
    ]
