# Generated by Django 5.1.2 on 2024-10-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_pointevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointevent',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
