# Generated by Django 5.1.2 on 2024-10-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_pointevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointevent',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
