# Generated by Django 5.1.2 on 2024-10-16 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_pointevent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
