# Generated by Django 5.1.2 on 2024-10-19 21:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_pointevent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=colorfield.fields.ColorField(default='#ee84d7', image_field=None, max_length=25, samples=None),
        ),
    ]
